// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxkjyiqMYUANXINf1ch6TFPgMQ7A2Pyi4',
    appId: '1:378138530827:web:9b4edcf7478dafba1ca30e',
    messagingSenderId: '378138530827',
    projectId: 'my-notes-project-d00f3',
    authDomain: 'my-notes-project-d00f3.firebaseapp.com',
    storageBucket: 'my-notes-project-d00f3.appspot.com',
    measurementId: 'G-77DKXFD5QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6So2vc5EvNOE5_WnBowCRP3W6A2hbrmM',
    appId: '1:378138530827:android:e4bb338746820b751ca30e',
    messagingSenderId: '378138530827',
    projectId: 'my-notes-project-d00f3',
    storageBucket: 'my-notes-project-d00f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFqtuIJjwi1X4nJWuxtX2LdpDKeuiInBQ',
    appId: '1:378138530827:ios:2d052c189617ac2a1ca30e',
    messagingSenderId: '378138530827',
    projectId: 'my-notes-project-d00f3',
    storageBucket: 'my-notes-project-d00f3.appspot.com',
    iosClientId: '378138530827-o8g61m96ru1m1mbtc95au0kai6p67lnb.apps.googleusercontent.com',
    iosBundleId: 'com.nguyenng.mynotes',
  );
}
